# Generated by Django 3.2.15 on 2022-08-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='id',
        ),
        migrations.AlterField(
            model_name='medication',
            name='concept_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
