# Generated by Django 3.2.15 on 2022-09-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20220824_0315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medication',
            new_name='ClinicalMedication',
        ),
    ]
