# Generated by Django 3.2.15 on 2022-09-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_commercialproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialproduct',
            old_name='clinical_medication_id',
            new_name='clinical_medication',
        ),
    ]
