# Generated by Django 3.2.15 on 2022-09-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_rename_clinical_medication_id_commercialproduct_clinical_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicMedication',
            fields=[
                ('concept_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='clinicalmedication',
            name='basic_medication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medications.basicmedication'),
            preserve_default=False,
        ),
    ]
